### ISSUE TITLE
Faceoverlay sample not working with openvidu openvidu/openvidu-server-kms:2.19.0

### ISSUE THREAD

**Issue by hartrene** [OpenVidu/openvidu-tutorials#163]
Openvidu version 2.19.0 throwing error when activating the Faceoverlay example.
Works ok with 2.16.0.

Error in the server logs:

´[ERROR] 2021-08-01 08:22:32,985 [SessionHandler-ecgihfei124i3dkkk0r4tbt0nm-e4-t0] org.kurento.jsonrpc.internal.JsonRpcHandlerManager - Exception while processing request {"id":20,"method":"applyFilter","params":{"streamId":"str_CAM_PKze_con_MOh3XwDq1r","type":"FaceOverlayFilter","options":"{}"},"jsonrpc":"2.0"}
org.kurento.client.internal.server.KurentoServerException: Unexpected error while processing method: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/persistence.cpp:6628: error: (-2) The node does not represent a user object (unknown type?) in function cvRead
 (Code:-32603, Type:null, Data: null)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.sendRequest(RomClientJsonRpcClient.java:264)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.create(RomClientJsonRpcClient.java:157)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.create(RomClientJsonRpcClient.java:147)
	at org.kurento.client.internal.client.RomManager.create(RomManager.java:59)
	at org.kurento.client.internal.client.RomManager.createWithKurentoObject(RomManager.java:257)
	at org.kurento.client.AbstractBuilder.build(AbstractBuilder.java:65)
	at io.openvidu.server.kurento.core.KurentoSessionManager.applyFilterInPublisher(KurentoSessionManager.java:1341)
	at io.openvidu.server.kurento.core.KurentoSessionManager.applyFilter(KurentoSessionManager.java:931)
	at io.openvidu.server.rpc.RpcHandler.applyFilter(RpcHandler.java:524)
	at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:155)
	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:142)
	at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)´

**Comment by j1elo** [comment]
Hi @hartrene , nice catch!

I've been asking around, and the issue seems to come from an update in the Docker base image. The owners of this code are currently on holidays, so we'll have to wait to get a fix for this.

Meanwhile, the only workaround I can suggest is that you avoid using this development image, and instead use a full OpenVidu deployment with the official production images. These don't have the same issue, and I've just tested that the latest OpenVidu 2.19 works fine with the FaceOverlay plugin.

Sorry for the inconvenience... we'll try to have this fixed soon!
